# Generated by Django 2.2 on 2021-08-24 03:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_jsonfield_backport.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OperationLogs',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('who_user', models.CharField(default='whomax', max_length=50, verbose_name='用户名称')),
                ('last_login', models.DateTimeField(verbose_name='最后一次登录时间')),
                ('who_ip', models.GenericIPAddressField(verbose_name='登录ip')),
                ('when', models.DateTimeField(default=django.utils.timezone.localtime, verbose_name='操作时间')),
                ('how', models.CharField(max_length=200, verbose_name='动作')),
                ('request_data', django_jsonfield_backport.models.JSONField(default=dict, null=True, verbose_name='请求的数据体')),
                ('what_before', django_jsonfield_backport.models.JSONField(default=dict, null=True, verbose_name='之前')),
                ('what_after', django_jsonfield_backport.models.JSONField(default=dict, null=True, verbose_name='之后')),
                ('where', models.CharField(max_length=50)),
                ('result', models.BooleanField(choices=[(True, '成功'), (False, '失败')], verbose_name='操作结果')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='组名称^^^^')),
                ('description', models.TextField()),
                ('pages', django_jsonfield_backport.models.JSONField(verbose_name='可访问页面')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.localtime, verbose_name='创建时间')),
                ('permission', models.TextField(default='非管理员')),
            ],
            options={
                'ordering': ['create_time'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.localtime, verbose_name='创建时间')),
                ('role', models.ManyToManyField(to='mydoc.Role')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mydoc.OperationLogs')),
            ],
            options={
                'ordering': ['create_time'],
            },
        ),
    ]
